before:
  hooks:
  - "go mod download"
builds:
- id: "release"
  env:
  - CGO_ENABLED=1
  main: "./cmd/zed"
  ldflags: "-s -w -X github.com/authzed/zed/internal/version.Version={{.Version}}"
  goos:
  # - "linux"
  # - "freebsd"
  # - "openbsd"
  - "darwin"
  goarch:
  - "amd64"
  - "arm64"
archives:
- id: "release"
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
- tap:
    owner: authzed
    name: homebrew
  folder: Formula
  homepage: https://github.com/authzed/zed
  description: manage authzed from your command line
  license: "Apache 2.0"
  dependencies: []
  test: |
    system "#{bin}/zed", "version"
# dockers:
#   - goos: linux
#     goarch: amd64
#     dockerfile: ./Dockerfile
#     image_templates:
#     - "quay.io/authzed/zed:{{.Version}}"
#     build_flag_templates:
#     - "--label=org.opencontainers.image.created={{.Date}}"
#     - "--label=org.opencontainers.image.name={{.ProjectName}}"
#     - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#     - "--label=org.opencontainers.image.version={{.Version}}"
#     - "--label=repository=https://github.com/authzed/zed"
#     - "--label=homepage=https://github.com/authzed/zed"
