---
name: "Build & Test"
on:
  push:
    branches:
      - "!dependabot/*"
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    name: "Go Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - name: "Build"
        run: "go build ./cmd/..."

  unit:
    name: "Run Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - uses: "authzed/action-testserver@main"
      - name: "ensure test server online"
        run: "curl localhost:50051 | base64"
      - name: "Run `go test`"
        run: "go test -race ./..."

  image-build:
    name: "Docker Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
        with:
          driver-opts: "image=moby/buildkit:master"
      - uses: "docker/build-push-action@v1"
        with:
          push: false
          tags: "latest"
