name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  goreleaser:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "docker/login-action@v1"
        with:
          registry: "quay.io"
          username: "${{ secrets.QUAY_USERNAME }}"
          password: "${{ secrets.QUAY_ROBOT_TOKEN }}"
      - name: "Install cross-compilers"
        run: |
          brew tap messense/macos-cross-toolchains
          brew install x86_64-unknown-linux-gnu
          brew install aarch64-unknown-linux-gnu
          brew install mingw-w64
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - uses: "goreleaser/goreleaser-action@v2"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HOMEBREW_TAP_GITHUB_TOKEN: "${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}"
