name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-mac:
    needs: "create"
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - id: "get_version"
        uses: "battila7/get-version-action@v2"
      - name: "build"
        run: |
          go build -o zed ./cmd/zed
          tar -cvf zed_${{ steps.get_version.outputs.version-without-v }}_darwin_amd64.tar.gz ./zed LICENSE README.md
      - uses: actions/upload-artifact@v2
        with:
          name: darwin_zed
          path: zed_${{ steps.get_version.outputs.version-without-v }}_darwin_amd64.tar.gz

  goreleaser:
    # goreleaser will create the homebrew update, needs the mac build to exist
    needs: "build-mac"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "docker/login-action@v1"
        with:
          registry: "quay.io"
          username: "${{ secrets.QUAY_USERNAME }}"
          password: "${{ secrets.QUAY_ROBOT_TOKEN }}"
      - id: "get_version"
        uses: "battila7/get-version-action@v2"
      - uses: actions/download-artifact@v2
        with:
          name: darwin_zed
          path: zed_${{ steps.get_version.outputs.version-without-v }}_darwin_amd64.tar.gz
      - name: "Install linux cross-compilers"
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - uses: "goreleaser/goreleaser-action@v2"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HOMEBREW_TAP_GITHUB_TOKEN: "${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}"